import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(root, "public");
mkdirSync(publicDir, { recursive: true });

const config = JSON.parse(
  readFileSync(join(root, "src", "site.config.json"), "utf8"),
);

const routes = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/download", changefreq: "weekly", priority: "0.9" },
  { path: "/features", changefreq: "monthly", priority: "0.8" },
  { path: "/security", changefreq: "monthly", priority: "0.8" },
  { path: "/documentation", changefreq: "monthly", priority: "0.7" },
  { path: "/changelog", changefreq: "weekly", priority: "0.6" },
  { path: "/faq", changefreq: "monthly", priority: "0.6" },
  { path: "/about", changefreq: "yearly", priority: "0.4" },
];

const siteUrl = String(config.siteUrl || "").replace(/\/+$/, "");
const today = new Date().toISOString().slice(0, 10);

let sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs. Configure "siteUrl" in src/site.config.json. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
`;
if (siteUrl) {
  for (const r of routes) {
    sitemap += `  <url>\n    <loc>${siteUrl}${r.path}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${r.changefreq}</changefreq>\n    <priority>${r.priority}</priority>\n  </url>\n`;
  }
} else {
  sitemap += `  <!-- Set "siteUrl" in src/site.config.json to generate real URLs. -->\n`;
}
sitemap += `</urlset>\n`;
writeFileSync(join(publicDir, "sitemap.xml"), sitemap, "utf8");

let robots = `# robots.txt — generated by scripts/generate-sitemap.mjs
User-agent: *
Allow: /
`;
if (siteUrl) {
  robots += `\nSitemap: ${siteUrl}/sitemap.xml\n`;
} else {
  robots += `\n# Set "siteUrl" in src/site.config.json to publish the sitemap reference.\n`;
}
writeFileSync(join(publicDir, "robots.txt"), robots, "utf8");

console.log(
  siteUrl
    ? `sitemap.xml and robots.txt generated for ${siteUrl}`
    : "sitemap.xml and robots.txt generated (siteUrl not set — configure src/site.config.json)",
);
